### ISSUE TITLE
Getting Metadata from some games in Epic erroring

### ISSUE THREAD

**Issue by Jhanlon95** [JosefNemec/PlayniteExtensions#165]
**Check for existing issue**
N/A

**Describe the bug**
When trying to get metadata from some games from Epic Games Store, I am seeing the error "Failed to download metadata: Object reference not set to an instance of an object."

Only seems to happen on some games, attempted on Dungeons 3 and City of Brass and they both were able to download metadata without issue

**To Reproduce**
The games that I have had this happen on are

- Astalon: Tears of the Earth
- Five Nights at Freddy's Security Breach
- Expedition Zero
- Inscryption

**Screenshots**
![image](https://user-images.githubusercontent.com/11045596/161388570-9f27a598-4c44-474a-bf6a-514c472a4f50.png)

**Entry within Playnite.log**

```
02-04 15:45:04.731|ERROR|GameEditViewModel:Failed to download metadata, 00000002-dbd1-46c6-b5d0-b1ba559d10e4, cdee87a39860471796c3be1d70a76beb
System.NullReferenceException: Object reference not set to an instance of an object.
   at EpicLibrary.Services.WebStoreClient.<GetProductInfo>d__6.MoveNext() in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\Services\WebStoreClient.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at EpicLibrary.EpicMetadataProvider.GetMetadata(Game game) in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\EpicMetadataProvider.cs:line 37
   at Playnite.DesktopApp.ViewModels.GameEditViewModel.<DownloadStoreData>b__483_0(GlobalProgressActionArgs args) in C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\GameEditViewModelMetadata.cs:line 555
   at Playnite.ViewModels.ProgressViewViewModel.<ActivateProgress>b__31_0() in C:\projects\playnite\source\Playnite\ViewModels\ProgressViewViewModel.cs:line 122
02-04 15:46:57.779|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.GameEditWindowFactory, False.
```

**Diagnostics ID**
262f6094-7db4-48f9-87c1-4fffeaf8a05d

**Comment by Jhanlon95** [comment]
Also having this happen with Bug Fables: The Everlasting Sapling, which was recently released on Epic Games Store

**Comment by JosefNemec** [comment]
Done in the latest update.
