### ISSUE TITLE
Importing new games from steam silently fails

### ISSUE THREAD

**Issue by brabulla** [JosefNemec/PlayniteExtensions#198]
**Describe the bug**
Some recently purchased games are not getting imported to Playnite when the Steam library integration runs the import.

The client shows no indication of error, but the games are not added to the library.

The playnite.log file shows the following error: 
```
TIMESTAMP|ERROR|GameDatabase:Failed to import game into database.
System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.TransactionService.PersistDirtyPages()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonType autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   at LiteDB.LiteCollection`1.Upsert(T document)
   at Playnite.Database.ItemCollection`1.Add(TItem itemToAdd) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 348
   at Playnite.Database.GamesCollection.Add(Game item) in C:\projects\playnite\source\Playnite\Database\Collections\GamesCollection.cs:line 85
   at Playnite.Database.GameDatabase.ImportGame(GameMetadata game, Guid pluginId) in C:\projects\playnite\source\Playnite\Database\GameDatabase.cs:line 1119
   at Playnite.Database.GameDatabase.ImportGames(LibraryPlugin library, Boolean forcePlayTimeSync, CancellationToken cancelToken) in C:\projects\playnite\source\Playnite\Database\GameDatabase.cs:line 1173
```

Some further info:
* Happens when running normally, and also when running as an admin
* Also happens in safe mode
* OS is Windows 11

**Diagnostics ID**
9b379111-e3bd-42b2-bec8-52604e391d1b

**Comment by JosefNemec** [comment]
Your library database file is corrupted, please attach `%AppData%\Playnite\library\games.db` file, I'll try to repair it.

**Comment by brabulla** [comment]
Thank you, created a zip, since Github did not let me upload a .db file.

[games.zip](https://github.com/JosefNemec/PlayniteExtensions/files/9087912/games.zip)

**Comment by JosefNemec** [comment]
[Here's fixed file.](https://github.com/JosefNemec/PlayniteExtensions/files/9090168/games_fixed.zip)

**Comment by brabulla** [comment]
Thank you, now it works perfectly!
