### ISSUE TITLE
Humble library sync fails: NullReferenceException

### ISSUE THREAD

**Issue by yo1dog** [JosefNemec/PlayniteExtensions#293]
Diagnostic ID: `a068f5f1-8e08-40c9-8715-cbff0d849304`

When I attempt to update/sync the Humble library, I get the following error and no games are imported:
```
08-06 18:49:26.841|ERROR|HumbleLibrary#HumbleLibrary:Failed to import general library Humble games.
System.NullReferenceException: Object reference not set to an instance of an object.
   at HumbleLibrary.HumbleLibrary.<>c.<GetLibraryGames>b__8_0(Order a) in E:\Devel\PlayniteExtensions\source\Libraries\HumbleLibrary\HumbleLibrary.cs:line 191
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HumbleLibrary.HumbleLibrary.GetLibraryGames() in E:\Devel\PlayniteExtensions\source\Libraries\HumbleLibrary\HumbleLibrary.cs:line 191
   at HumbleLibrary.HumbleLibrary.ImportGames(LibraryImportGamesArgs args) in E:\Devel\PlayniteExtensions\source\Libraries\HumbleLibrary\HumbleLibrary.cs:line 246
```

I tried uninstalling that reinstalling the add-on and re-authenticating with no luck. Let me know if I can provide any more info. The sync has never worked for me.

In addition to above, this was all I saw in the logs the looked related:
```
08-06 18:59:41.945|DEBUG|Downloader:Downloading data from https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_6.pext to C:\Users\Mike\AppData\Local\Temp\Playnite\HumbleLibrary_Builtin.pext.
...
08-06 19:00:04.649|INFO |ExtensionInstaller:Installing extenstion/theme C:\Users\Mike\AppData\Local\Temp\Playnite\HumbleLibrary_Builtin.pext
08-06 19:00:04.802|INFO |ExtensionInstaller:Installed extension C:\Users\Mike\AppData\Local\Temp\Playnite\HumbleLibrary_Builtin.pext
...
08-06 19:00:05.320|INFO |ExtensionFactory:Loaded plugin: Humble library integration, version 3.6
...
08-06 19:00:13.327|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/HumbleLibrary_Builtin.yaml using UTF8 encoding.
...
08-06 19:02:19.281|INFO |MainViewModelBase:Importing games from Humble plugin.
```

Let me know if there is any additional information that I can provide.

**Comment by yo1dog** [comment]
Sorry for delay, I was out.

Same error as before. Diagnostic ID: `d4984a40-0062-4ee8-a70d-75d24db80dd8`

**Comment by yo1dog** [comment]
Works. Thanks!
