### ISSUE TITLE
Xbox plugin doesn't authenticate

### ISSUE THREAD

**Issue by XenorPLxx** [JosefNemec/PlayniteExtensions#338]
**Check for existing issue**
No similar issues found on Github, there were otherrs reporting on Discord.

**Describe the bug**
When refreshing the library Xbox pluging errored out:
```
01-12 01:27:21.306|ERROR|XboxLibrary#XboxLibrarySettingsViewModel:Failed to authenticate user.
System.NullReferenceException: Object reference not set to an instance of an object.
   at XboxLibrary.Services.XboxAccountClient.<Authenticate>d__8.MoveNext() in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:line 159
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XboxLibrary.Services.XboxAccountClient.<Login>d__6.MoveNext() in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XboxLibrary.XboxLibrarySettingsViewModel.<Login>d__9.MoveNext() in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\XboxLibrarySettingsViewModel.cs:line 59
```
After trying to reauthenticate, it goes through the authentication process successfully but registers authentication, going back in circles.

I tried removing contests of plugins data folder and clearing web cache, didn't help.

**To Reproduce**
Seems like logging in on a freshly installed add-on with no web cache is enough to trigger the bug, at least on my account.

**Screenshots**
Recording from another user on Discord, mine behaves the same.
https://github.com/JosefNemec/PlayniteExtensions/assets/6712823/24d38662-1936-4f31-995e-439d1c3d7af3

**Diagnostics ID**
4635bd23-3671-4ca9-9171-2adeaeb9f75d

**Comment by Albertron86** [comment]
same problem

**Comment by jamie-dit** [comment]
Same issue here on a new install

**Comment by jdwrhodes** [comment]
Same issue for me too.

**Comment by Caddie2908** [comment]
Same problem here .... No authentification possible ....

**Comment by JosefNemec** [comment]
Please stop with "same issues" posts. We know that it's broken and why, as I said in my previous message. These posts only spam my inbox.

**Comment by JosefNemec** [comment]
Fixed in 2.13 update

**Comment by ivanmestre** [comment]
Hi, @JosefNemec. While the Authentication issue seems to be fixed on update 2.13, it seems to require reauthentication after 24 hours. There's a 400 error when refreshing the Auth token after 24 hours. This is the log:

`06-12 11:21:21.449|DEBUG|XboxLibrary#XboxAccountClient:Refreshing xbox tokens.
06-12 11:21:21.840|ERROR|XboxLibrary#XboxLibrary:Failed to Xbox profile titles.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at XboxLibrary.Services.XboxAccountClient.<ExecuteTokenRequest>d__12.MoveNext() in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XboxLibrary.Services.XboxAccountClient.<RefreshOAuthToken>d__11.MoveNext() in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XboxLibrary.Services.XboxAccountClient.<RefreshTokens>d__14.MoveNext() in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XboxLibrary.Services.XboxAccountClient.<GetLibraryTitles>d__15.MoveNext() in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:line 263
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at XboxLibrary.XboxLibrary.GetGames(LibraryGetGamesArgs args) in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\XboxLibrary.cs:line 193
06-12 11:21:24.279|ERROR|XboxLibrary#XboxLibrary:Failed to get info about installed UWP package Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe.
System.Exception: User is not authenticated.
   at XboxLibrary.Services.XboxAccountClient.<GetTitleInfo>d__17.MoveNext() in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:line 358
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at XboxLibrary.XboxLibrary.GetGames(LibraryGetGamesArgs args) in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\XboxLibrary.cs:line 246
06-12 11:21:25.295|ERROR|XboxLibrary#XboxLibrary:Failed to get info about installed UWP package Microsoft.SecHealthUI_8wekyb3d8bbwe.
System.Exception: User is not authenticated.
   at XboxLibrary.Services.XboxAccountClient.<GetTitleInfo>d__17.MoveNext() in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:line 358
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at XboxLibrary.XboxLibrary.GetGames(LibraryGetGamesArgs args) in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\XboxLibrary.cs:line 246
06-12 11:21:26.342|ERROR|XboxLibrary#XboxLibrary:Failed to get info about installed UWP package Microsoft.Winget.Source_8wekyb3d8bbwe.
System.Exception: User is not authenticated.
   at XboxLibrary.Services.XboxAccountClient.<GetTitleInfo>d__17.MoveNext() in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:line 358
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at XboxLibrary.XboxLibrary.GetGames(LibraryGetGamesArgs args) in C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\XboxLibrary.cs:line 246
06-12 11:21:26.342|DEBUG|XboxLibrary#XboxLibrary:Found 8 installed Xbox games.`

Should I create a separate issue about this?

**Comment by riggsmarkham** [comment]
Encountering this issue on 10.33. I enter my login info and then the authentication screen goes blank and then never closes.

**Comment by matthewraykeller** [comment]
I am also unable to authenticate. I have tried safe mode and every possible combination of steps I can come up with. It just blinks after the authentication pop-up window closes at the end of the process and says it still needs authentication. I am on the latest versions and a fresh install.

9c232ef8-6b75-4fe7-9815-bce5bb001e19

**Comment by danburbul** [comment]
> Encountering this issue on 10.33. I enter my login info and then the authentication screen goes blank and then never closes.

I had to remove and reinstall the Xbox library plugin to resolve this.

**Comment by riggsmarkham** [comment]
> Encountering this issue on 10.33. I enter my login info and then the authentication screen goes blank and then never closes.

After updating to 10.34, this issue has been resolved for me.

**Comment by DustbinK** [comment]
Still occurring for me on 10.34 and after uninstalling and reinstalling the Xbox plugin. I sign in via Github and it always closed the window before I get the authentication request on my phone. Tried the alternative web view rendering mode and same behavior there.
